{% set name = "yt-napari" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/yt_napari-{{ version }}.tar.gz
  sha256: bd44c105cde9c7fa79ba915a273e3c4ead1ddaf1394b81d4718a6e7d4b1e8ede

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - magicgui >=0.6.1
    - napari >=0.4.19
    - numpy
    - packaging
    - pydantic
    - python >={{ python_min }}
    - qtpy
    - unyt
    - yt >=4.0.1

test:
  imports:
    - yt_napari
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/yt-napari
  summary: A napari plugin for loading data from yt
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/data-exp-lab/yt-napari

extra:
  recipe-maintainers:
    - chrishavlin
    - goanpeca
    - jaimergp
